### ISSUE TITLE
Errores de ajuste

### ISSUE THREAD

**Issue by ale-mendez** [diegoChocobar/SEV_1000_WS#5]
Calcular y mostrar los errores de ajuste. Esto podría ir codeado en python y se pasa a frontend como otro elemento del diccionario que devuelve los cálculos de python.

**Comment by diegoChocobar** [comment]
Me parece perfecto lo que propones, y el resultado del error del ajuste lo deberiamos mostrar como un subtitulo dentro del grafico.
